name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libavahi-compat-libdnssd-dev libplist-dev libssl-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-libav gstreamer1.0-vaapi gstreamer1.0-plugins-bad
    - name: create environment
      run: mkdir build
    - name: run CMAKE
      run: cd build && cmake ..
    - name: build
      run: cd build && make -j && ls -la
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/rpiplay"
        token: ${{ secrets.GITHUB_TOKEN }}
